name: Actualizacion Automatica Diaria
on:
  schedule:
    # Intento 1: 3:00 AM Perú (8:00 AM UTC) - Para tener margen de sobra
    - cron: '0 8 * * *'
    # Intento 2: 4:30 AM Perú (9:30 AM UTC) - Por si el primero se retrasa
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install pandas requests

      - name: Ejecutar script Los Brujos
        run: python actualizar_datos.py

      - name: Ejecutar script Yaurilla
        run: python actualizar_yaurilla.py

      - name: Guardar cambios en ambos CSV
        run: |
          git config --global user.name 'Robot Meteorologico'
          git config --global user.email 'bot@fundo.com'
          # Agregamos los dos archivos CSV
          git add datos_actualizados.csv datos_yaurilla.csv
          git commit -m "Robot: Data actualizada (Brujos y Yaurilla)" || exit 0
          git push
